# Generated by Django 5.2.4 on 2025-10-04 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultrelay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
