# Generated by Django 5.2.4 on 2025-10-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultrelay_app', '0002_usersignup_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='inactivity_email_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='inactivity_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='is_marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
